const Head = () => {
    return (
        <>
            <title>Create T3 App</title>
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <meta
                name="description"
                content="Generated by create-t3-app"
            />
            <link
                rel="icon"
                href="/favicon.ico"
            />
        </>
    );
};

export default Head;
